### PR TITLE
Allow SQL projections to be functions containing commas

### PR DESCRIPTION
**Pull request by grantcopley**
We ran into as issue where using DATEPART( iso_week, c.createdTime ) would blow up because it was using the same alias.

### CODE REVIEW

**Comment by jclausen** [comment]
@lmajano could we fast-track this one? It is a blocker for a client project. Thanks!

**Comment by lmajano** [comment]
It seems the formatting is blowing up tons of comments @grantcopley can you verify this.  Also, can I get a test case for this please.

**Comment by jclausen** [comment]
@lmajano The formatting changes came from your GitHub actions configuration ( committed by actions-bot https://github.com/coldbox-modules/cborm/pull/51/commits/5f5220cb4b42faf7e0a5b7389c2fb02a91abeab2 )

@grantcopley Since Luis uses MySQL for testing, you can probably use DATE_DIFF for your test case: https://dev.mysql.com/doc/refman/8.0/en/date-and-time-functions.html#function_datediff

**Comment by grantcopley** [comment]
@lmajano Test case added

**Pull request merged**
